version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'uvicorn app.main:app --host 0.0.0.0'
    container_name: web
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - POSTGRES_URL=${DOCKER_POSTGRES_URL}
      - WEB_DOMAIN=${DOCKER_WEB_DOMAIN}
      - WEB_PORT=${DOCKER_WEB_PORT}
      - REDIS_HOST=${REDIS_DOCKER_HOST}
      - REDIS_PORT=${DOCKER_REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - ELASTIC_PORT=${DOCKER_ELASTIC_PORT}
    depends_on:
      db:
        condition: service_healthy
      es01:
        condition: service_healthy
      cache:
        condition: service_healthy
    

  db:
    image: postgres:15-alpine
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - ${POSTGRES_PORT}:${DOCKER_POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  

  cache:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - ${REDIS_PORT}:${DOCKER_REDIS_PORT}
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
  

  es01:
    image: elasticsearch:7.17.12
    container_name: es01
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - ${ELASTIC_PORT}:${DOCKER_ELASTIC_PORT}
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://es01:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    ulimits:
      memlock:
        soft: -1
        hard: -1
  

  kibana:
    image: kibana:7.17.12
    container_name: kibana
    volumes:
      - kibana-data:/usr/share/kibana/data
    ports:
      - ${KIBANA_PORT}:${DOCKER_KIBANA_PORT}
    environment:
      - 'ELASTICSEARCH_HOSTS=http://es01:${DOCKER_ELASTIC_PORT}'
    depends_on:
      - es01
    restart: always

volumes:
  postgres_data:
  data01:
    driver: local
  kibana-data:
    driver: local